version: '3.1'

services:
  postgresqldb:
    container_name: record_book
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=record_book